### PR TITLE
Epita logo in the javascript console and links opened in a new tab

### PR DESCRIPTION
**Pull request by thisiskeanyvy**
- I suggest opening the links in a new tab to make it easier to find what you're looking for. (grid-loader.html, default.html)
- I also suggest displaying the Epita logo encoded in ASCII in the JavaScript console. (script.js)

console

### CODE REVIEW

**Comment by matiboux** [comment]
I have several questions.

### About `target="_blank"`

The point of EPITA.it is to be a page you leave to go elsewhere.

Most of the time, I'd say the user knows where he wants to go when they visit EPITA.it.
Do you agree?

My personal use case is often: typing "epi" in my browser, auto-completing the URL, clicking on Pegasus and be done.

Can forcing opening links in a new tab be a useful feature?
Or would it be just annoying overhead to keep a tab most people would have to close manually?

### About the user warning logo in the console

Ascii art in the console is a fun idea.
However, why is the ascii background (with `@` characters) chunky?

Wouldn't it be better to have a rectangular filled background with `@` characters?
Or better yet: no background at all, and just use ascii characters for the logo itself.
What do you think?

### About the user warning in the console and self-XSS.

EPITA.it is a stateless static website with no authentication data, no API.
This warning message is useless for a static website.

Also I'm sure many EPITA students opened the devtools in Discord and happily ignored the warning, even though token grabbing attacks are a real thing in such applications storing authentication data (which, once again, EPITA.it is not).

So, why should a huge warning message be shown?

**Comment by thisiskeanyvy** [comment]
<p align="justify">@matiboux I appreciate your questions and concerns regarding the points raised in my previous response. While I understand your perspective on the matter, I still believe there are valid arguments in favor of opening links in a new tab. Allow me to address your questions in a technical manner :</p>

## About target="_blank":
<p align="justify">The intention of epita.it is indeed to serve as a gateway for users to navigate elsewhere. However, it is important to consider that users may not always have a predetermined destination in mind when visiting the site. In such cases, opening links in a new tab can provide a seamless browsing experience by allowing users to explore external content without interrupting their current context.</p>

<p align="justify">While it is true that many users may have a specific destination in mind when visiting epita.it, it is also worth acknowledging that different users have different browsing habits and preferences. By providing the option to open links in a new tab, we cater to a wider range of user behaviors, enhancing their overall experience.</p>

### Can forcing the opening of links in a new tab be a useful feature?
<p align="justify">The usefulness of opening links in a new tab largely depends on the specific user and their browsing habits. While it may be seen as an overhead for some users to manually close tabs, others may find it beneficial to have multiple tabs open for reference or easy navigation.</p>

<p align="justify">It is important to strike a balance between providing convenience and avoiding unnecessary clutter. One approach to mitigate this issue is to give users the choice to configure their browsing preferences, either by providing a setting or through a contextual option when clicking on a link.</p>

## About the user warning logo in the console:
<p align="justify">The use of ASCII art in the console can indeed be a fun and creative idea. Regarding the chunkiness of the ASCII background, using a rectangular filled background with "@" characters may result in a more visually appealing and consistent display. Alternatively, opting for no background and solely using ASCII characters for the logo itself can provide a cleaner and more focused representation.</p>

<p align="justify">Ultimately, the decision on the design and appearance of the warning logo should consider factors such as readability, aesthetics, and adherence to the overall visual style of Epita.</p>

## About the user warning in the console and self-XSS:
<p align="justify">I understand that epita.it is a static website without authentication data or an API, rendering the warning message seemingly unnecessary. However, it's important to acknowledge that security risks and best practices extend beyond the specific functionalities of a website.</p>

<p align="justify">While epita.it may not store authentication data, it is possible that some users are accustomed to seeing warning messages in similar web applications and might associate it with security measures. It can serve as a reminder to users about potential security threats in other contexts, even if they do not directly apply to epita.it.</p>

<p align="justify">Balancing user experience with security considerations is crucial, and it may be worth exploring alternative ways to educate and inform users about potential risks, while ensuring the message is contextually relevant and impactful.</p>

I hope these arguments provide a deeper insight into the various aspects to be considered.
Feel free to further discuss any points or raise additional concerns.

**Comment by matiboux** [comment]
Thank for your reply, ChatGPT.

Very instructive, your point of view basically says the best thing to do is to give user more options and choices, when your pull request actually forces all users to open links in a new tab and therefore reducing ease of use and choices.

The pull request is likely to be closed.

The pull request also is not atomic and has too many changes to be reviewed.

If you still want to, you can open another pull request with only the ASCII art, as it is the only change that would be likely to merge at the moment.

**Comment by thisiskeanyvy** [comment]
I agree with the ASCII but I'd like to add in the next PR, the removal of google analytics and links to google fonts. Because with these, the site doesn't seem to be compliant with the CNIL, and it would be good to do this soon to avoid any potential complaints and their consequences from my point of view.

**Comment by thisiskeanyvy** [comment]
https://thisiskeanyvy-hosting.pages.dev/docs/uYAEYdTgHDXUKoROaATgUhnuFUSdzmVwpby3cS5bh5AQQ8hjbPT0q7CCttSt_210310_07122022.pdf

**Pull request closed without merging**
